- gufe/__init__.py
- gufe/chemicalstate.py
Microstates is a stat mech loaded term - asking as someone that still has to deal with profs regularly, can we just avoid it 🙃 
Here I propose ChemicalState. The idea being that ChemicalState(s) are real states that are joined by various AlchemicalStates along a free energy network.
That being said, if the intent is to truly represent a very specific microstate of a system (which didn't seem the case from this week's F@H alchemy call), then that's a different issue...
> Request to rename/avoid MicroState

- environment.yml
- gufe/chemicalstate.py
Included `__init__` for core set of attributes for `ChemicalState` from working session with @richardjgowers. Assumes that `ChemicalState` components are all RDKit molecules, and that that the `ChemicalState` is immutable upon instantiation.
> Added initial attributes and methods for ChemicalState

- gufe/solventcomponent.py
- gufe/tests/test_chemicalsystem.py
- gufe/tests/test_solvents.py
- if given, must give exactly two ions, one position one negative
- force use of kwargs to initialize
- rename concentation to ion_concentration
- added usage example
- allows ions=None rather than empty tuple
> Tightening up `SolventComponent`

- gufe/chemicalsystem.py
- gufe/tests/test_chemicalsystem.py
In starting to write code that might use this, I'm finding that `chemical_system.components['thing']` is coming up over and over again. I propose making `ChemicalSystem` an `abc.Mapping`, so that we can use it as `chemical_system['thing']`.
> Make `ChemicalSystem` an `abc.Mapping`

- .coveragerc
`exclude_lines` in `.coveragerc` is a list of regular expressions, not literal strings. Therefore including the string `...` caused all lines to be excluded from coverage. This fixes the problem.
> Fix coveragerc ellipsis exclusion

- gufe/solventcomponent.py
- gufe/tests/test_solvents.py
Life is a lot easier if we play by the rule that the dict that comes out of to_dict should be JSON serializable. Quantities are not.
Choice is either create custom JSON encoders/decoders, or require to_dict to return something JSON serialization.
In this PR, I only changed SolventComponent.ion_concentration. I may come across others as I work my way through storage.
> to_dict on unitted quantities should use to_tuple

- gufe/solventcomponent.py
- gufe/tests/test_solvents.py
If both ions are `None` and `neutralize=True` (as is the default) behavior is unclear if the system needs to be neutralized. This changes the defaults to "Na+" and "Cl-".
Second commit here disallows `None` as a valid value. I don't think there's any reason to allow it if it isn't the default, right?
While I'm at it, should I also change default on `ion_concentration` to 0.0 molar, instead of `None`?
> Change ion defaults

- gufe/protocols/__init__.py
- gufe/protocols/protocoldag.py
- gufe/protocols/protocolunit.py
- gufe/protocols/results.py
- gufe/tests/test_protocol.py
I think it might make sense for the result of an individual piece of work to return either a "good" or "bad" results object.  I think Exceptions are enough for some failure reasons (out of disk space, incomplete inputs, unsuitable compute environment) but by returning more than just an exception, you could make the chemistry failures a lot more useful.
It could be that we can make the `ok()` method below just an attribute of a single Result class, since the schema for a `ProtocolUnitResult` is fairly loose/nonexistant.  I'm undecided if there's value in having two schema, one for results and one for error introspection.
One annoyance of first class errors is we'd have to teach schedulers how to identify these so they correctly interrupt a dependency chain.  I think there's probably a …
> added Failure result

- gufe/components/solventcomponent.py
- gufe/tests/test_solvents.py
I think @dwhswenson asked about this and we forgot to implement, it seems neater to always have this exist rather than `None` sometimes
> Solvent: make concentration always a unit, even if 0.0M

- gufe/protocols/protocol.py
- gufe/tokenization.py
As @RiesBen noted in https://github.com/OpenFreeEnergy/gufe/pull/45#discussion_r974148678, leaving the body of an abstract method as `...` can return `None`. I'm not too worried about this for instance methods, where the `abc.abstractmethod` decorator prevents us from instantiating if unimplemented (although you can still do `AbstractClass.abstract_method(self=explicit_object, ...)`).
However, classmethods are typically called without instance, as `ClassName.class_method(...)`. The `abc.abstractmethod` decorator does nothing to protect us there.
This PR ensures that all abstract class methods raise `NotImplementedError`. (I went ahead and changed the abstract `_to_dict` as well, so that it matches `_from_dict`.)
> Raise NotImplementedError in abstract classmethods

- gufe/tokenization.py
Small fix, shouldn't impact code correctness, just typing.
> Small fix to typing of TOKENIZABLE_REGISTRY

- gufe/components/proteincomponent.py
Getting errors on OpenFE PRs with `ModuleNotFoundError: No module named 'gufe.vendor'` -- hoping this is all that is needed to fix.
> Add __init__.py to vendor/

- gufe/components/explicitmoleculecomponent.py
- gufe/molhashing.py
- gufe/tests/test_smallmoleculecomponent.py
- gufe/tests/test_tokenization.py
- gufe/tokenization.py
Main goal here is to add a test to `GufeTokenizableTestsMixin` that will automatically test that the full `to_dict`/`from_dict` cycle works if the `TOKENIZABLE_REGISTRY` has been cleared, to mock deserializing in a different process from the serialization.
This led to some weirdness:
* I got the same problem with `WeakValueDictionary` that I mentioned this morning; where I get a `KeyError`, but if you drop into the pdb on error, the key is in the dict. I fixed this by putting a `try`/`except` around that.
* There is a genuine error in serialization of `SmallMoleculeComponent`. It's because we serialize with explicit hydrogens, but don't force explicit hydrogens when we take in an rdkit molecule. So the original ethane has smiles `CC` and the deserialized one has …
> Add test for roundtrip with cleared registry

- gufe/protocols/protocolunit.py
```python
In [1]: v = ValueError("foo")
In [2]: str(type(v))
Out[2]: "<class 'ValueError'>"
In [3]: v.__class__.__qualname__
Out[3]: 'ValueError'
```
I think what we wanted was the latter, not the former -- at least, if we're going to try to reassemble the error message.
> Fix the way exception class names are made strings

- gufe/protocols/__init__.py
- gufe/protocols/protocoldag.py
- gufe/protocols/protocolunit.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocol_unit.py
- gufe/tests/test_tokenization.py
- gufe/tests/test_transformation.py
This change raises the error from a given ProtocolUnit.execute call if `raise_error=True`. In `protocoldag.execute`, giving this same kwarg will cause the method to stop on hitting an exception in the ProtocolUnit it is executing. This makese debugging easier when necessary.
> Added raise_error kwarg for protocoldag.execute, ProtocolUnit.execute

- gufe/protocols/protocoldag.py
- gufe/protocols/protocolunit.py
- gufe/tests/test_protocol.py
Somewhat of a rebuttal to #102
Allows many `ProtocolUnitResult`s per `ProtocolUnit` in a `ProtocolDAGResult`
> Protocoldagresult multiple results

- gufe/protocols/protocoldag.py
- gufe/tests/test_protocol.py
This gives parity with the other properties on this object.
> Made ProtocolDAGResult.terminal_protocol_unit_results a property

- gufe/tests/conftest.py
This essentially makes our predefined PDB loaders session-scoped. This cuts out a lot of network activity and should give us as notable speedup when running the full test suite.
In principle, it would probably be better to structure everything to use the `request` fixture, but this is a smaller code change for essentially the same result.
> Speed up protein test loading

- docs/api/protocols.rst
- docs/guide.rst
- docs/guide/serialization.rst
This will add some developer-facing documentation on `gufe` serialization.
> [DOCS] Serialization

- gufe/storage/metadatastore.py
- gufe/tests/storage/test_metadatastore.py
(This includes and extends #21, and should be merged/reviewed after that one is merged.)
This adds `PerFileJSONMetadataStore`. The original `JSONMetadataStore` wrote all metadata (hashes) to a single JSON file. That is unlikely to be optimal for many workflows. The approach used in this object creates a separate label at `metadata/{filename}.json`, corresponding to a JSON file with an object carrying the metadata. This way, we don't need to completely re-export all metadata every time we store an new object.
> Add PerFileJSONMetadataStore

- MANIFEST.in
We had not been including test data in MANIFEST.in, meaning that `pytest --pyargs gufe` would fail because the files weren't including in the installation.
I know that @richardjgowers has been talking about moving to a separate package to manage test data. That may be a better solution than this, but it would be nice to push out a release with this quickly: (1) running tests is one of the first things I recommend when a user has an installation issue (can often point to problems like this); (2) I think this is blocking OpenFreeEnergy/openfe#266.
> Add test data to MANIFEST.in

- gufe/__init__.py
- gufe/protocols/protocol.py
- gufe/settings/__init__.py
- gufe/settings/models.py
- gufe/tests/test_protocol.py
- gufe/tests/test_transformation.py
Updates the tests around `DummyProtocol` to use a `Settings` object internally, making the tests more relevant for real world cases
> Update Protocol tests to use Settings object

- gufe/components/explicitmoleculecomponent.py
- gufe/components/smallmoleculecomponent.py
- gufe/mapping/ligandatommapping.py
- gufe/tests/conftest.py
- gufe/tests/data/ethane.sdf
- gufe/tests/test_chemicalsystem.py
- gufe/tests/test_ligandatommapping.py
- gufe/tests/test_mapping.py
- gufe/tests/test_network.py
- gufe/tests/test_smallmoleculecomponent.py
- gufe/tests/test_tokenization.py
- gufe/tests/test_transformation.py
- gufe/tokenization.py
This ensures that only one `GufeTokenizable` exists in memory for any given gufe key.
Consider this more a proposal than a request to merge.
Significant changed behavior:
* `tokenizable.copy_with_replacements()` (with no args) used to give a distinct copy in memory. It no longer does this, since no two different objects in memory can have the same gufe key.
* several tests in `SmallMoleculeComponent` are now meaningless -- there were a bunch of tests predicated on the idea that two molecules were equal but not the same in memory. This is now testing tautologies (I had put a test in to ensure that those tests were not testing tautologies; that extra test is now failing).
* removed concept of ofe-version from SMC
* serialise the `_rdkit` mol rather than going via openff.  this should …
> Make `GufeTokenizable` use a true flyweight pattern

- .github/workflows/ci.yaml
- pyproject.toml
In this PR:
- Check version import in CI
- fixes universal wheel
> Just checking version import

- gufe/chemicalsystem.py
- gufe/network.py
- gufe/transformations/transformation.py
This does a little cleanup, mainly things that fix up RST (missing escape to fix plurals; lack of roles defined).
This will fix some issues in openfreeenergy/openfe#325.
> Docs cleanup

- .github/workflows/clean_cache.yaml
We only get 10gb of cache per repo, and conda envs are chonks so we are close to the limit. When we hit the limit, the oldest entry gets evicted which could cause some cache thrashing. This PR at least will delete cache entries we don't need anymore.
> Delete cache from closed PRs

- gufe/protocols/protocol.py
- gufe/settings/models.py
- gufe/tests/test_protocol.py
PR into the changes already in #169; @richardjgowers's readonly settings. Now raises `TypeError` if you try to mutate after settings get attached to a protocol.
Might be nice for something with more pydantic experience than me to look this over? But tests pass locally, at least.
> Improved readonly settings

- environment.yml
> Fix packaging issues

- gufe/components/proteincomponent.py
helps with some nonstandard residues previously giving KeyError AROMATIC
will not affect serialised representations (i.e. keys) as these don't use this path
> proteincomponent: tweak conversions to/from openmm/rdkit

- docs/api.rst
- docs/api/transformation.rst
- gufe/transformations/transformation.py
This fixes the warnings causing RTD to choke on https://github.com/OpenFreeEnergy/openfe/pull/493 and also adds `Transformation` and `NonTransformation` to the GUFE API reference (for good measure).
Previously, several properties in both classes had docstrings AND an `Attributes` entry in the class docstring. This meant that they were documented twice, which Sphinx gets grumpy about. The documentation was also not identical, so readers noticing one might have missed information present only in the other. I've consolidated the documentation and type hints into the property docstrings and annotations. I've also fixed some errors arising because ReST is very picky about trailing `s`s after code spans and italicised regions and so on - so for example, I've changed `` `ChemicalSystem`s `` to …
> Transformation docstrings fixes

- gufe/tokenization.py
When the `inspect` module of the standard library is used to get the signature of a `GufeTokenizable` class, it sees that the metaclass has an implementation of `__call__` and takes the signature from that instead of from the `__new__` or `__init__` method of the child class:
```python
>>> from gufe import SmallMoleculeComponent
>>> import inspect
>>> inspect.signature(SmallMoleculeComponent)
<Signature (*args, **kwargs)>
>>> inspect.signature(SmallMoleculeComponent.__init__)
<Signature (self, rdkit: rdkit.Chem.rdchem.Mol, name: str = '')>
```
This results in unhelpful API documentation:
But also may affect the signature displayed by IDEs, the Jupyter `help` magic, and so on.
This PR restores the signature from `__init__` or `__new__` when a child class is created:
(I've taken screenshots …
> Prevent `_GufeTozenizableMeta.__call__` from overwriting signature of `__init__`

- gufe/ligandnetwork.py
- gufe/tests/test_ligand_network.py
@richardjgowers asked for a method on `LigandNetwork` to attach the protocol. This effectively moves some of the easy-planner stuff into gufe, but this aspect of it is likely to be broadly useful.
So far, a first glance of what I see the API looking like. Rough code, completely untested. Please take a look and see if this is the direction I should continue!
> LigandNetwork.to_*_alchemical_network

- docs/api.rst
- docs/api/components.rst
- docs/api/serialize.rst
- docs/api/tokenization.rst
- docs/api/transformation.rst
- docs/conf.py
- gufe/chemicalsystem.py
- gufe/components/component.py
- gufe/components/proteincomponent.py
- gufe/components/smallmoleculecomponent.py
- gufe/components/solventcomponent.py
- gufe/mapping/ligandatommapping.py
- gufe/network.py
- gufe/protocols/protocol.py
- gufe/protocols/protocoldag.py
- gufe/protocols/protocolunit.py
- gufe/tokenization.py
This PR moves more docstrings out of `attribute` sections of docstrings and onto the corresponding object itself. This helps comprehensive API documentation in OpenFE. Required by https://github.com/OpenFreeEnergy/openfe/pull/527
> Improve docstrings as needed for OpenFE

- gufe/protocols/protocolunit.py
- gufe/tests/test_protocolunit.py
This PR is an attempt to address openforcefield/alchemiscale#132.
@mikemhenry raised a good point that for the case of a `KeyboardInterrupt`, even if `raise_error = False` for `ProtocolUnit.execute`, we probably always want to raise.
Is there any downside to this?
> Always raise, don't swallow exception, if exception is `KeyboardInterrupt` in `ProtocolUnit.execute`

- gufe/custom_codecs.py
- gufe/tests/test_custom_json.py
Roundtripping of **arrays** of Quantity objects would previously fail
> Fix quantity array codec

- docs/conf.py
- docs/environment.yaml
This theme just adapts and updates the CSS from ``openfe`` to a new theme so it can be shared across all OpenFE projects. I've chosen the FeelingFabulous accent color to distinguish gufe, but this can easily be changed!
> Switch to OFE theme

- gufe/protocols/protocoldag.py
> Clarify "DAG dependency order" in docstrings

- gufe/visualization/mapping_visualization.py
This pull request adds one nice small features to gufe mapping visualization:
- labeling mapped molecules with their `ofe-name`
> adding mol name labels from ofe-name to mapping vis

- gufe/storage/stagingserialization.py
- gufe/storage/storagemanager.py
- gufe/tests/storage/test_stagingserialization.py
This is a subset of the work in #234, split off to facilitate review. This PR will merge into #258 (making it easier to see the additions specific to the PR, but meaning that this should be merged before that)
This handles the serialization of `StagingPath` objects. (detailed description will be coming in a future edit)
TODO:
> [WIP] Serialization of StagingPaths

- gufe/ligandnetwork.py
- gufe/protocols/protocol.py
- gufe/tests/test_ligand_network.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocoldag.py
- gufe/transformations/transformation.py
was previously a `dict[str, ComponentMapping]` where the strings were arbitrary labels.  These arbitrary labels were superfluous.  Instead can use the arbitrary labels on ChemicalSystems to label components.  (ComponentMappings can (and should) be matched against components in ChemicalSystem using the Component eq operations.)
This now accepts either a single ComponentMapping (covers most cases), or None (covers ABFE), or a list (handles future things?)
also affects Transformation object, which was essentially wrapper around Protocol + ChemicalSystem
> change signature of Protocol.create to have a list of ComponentMappings

- gufe/protocols/protocol.py
- gufe/settings/models.py
- gufe/tests/conftest.py
- gufe/tests/test_alchemicalnetwork.py
- gufe/tests/test_models.py
- gufe/tests/test_protocol.py
- gufe/tests/test_transformation.py
Adds `Settings.frozen_copy` and `Settings.unfrozen_copy` to create immutable/mutable versions of Settings object.  These freezes are recursive and apply to all contained Settings too.
Protocols now freeze their Settings on creation.  This should stop mistakes around modifying a Protocol's Settings in place.
> Readonly settings

- gufe/settings/models.py
adds _ipython_display_ to SettingsBaseModel
this pretty prints the nested settings
> fixes issue #263

- gufe/mapping/ligandatommapping.py
- gufe/tests/test_ligandatommapping.py
Adds a check to LigandAtomMapping that indices are possibly within the molecules.  E.g. if I provide index 100 to a molecule with 10 atoms then something isn't correct and I can provide an error immediately.
> Issue 170 lam validators

- gufe/custom_codecs.py
- gufe/tests/test_custom_json.py
- gufe/tokenization.py
Adds a codec for serialising UUIDs inside GUFE objects when provided as instances of `uuid.UUID`
Fixes #293
> Add UUID JSON codec

- gufe/settings/models.py
- gufe/tests/test_alchemicalnetwork.py
- gufe/tests/test_custom_json.py
- gufe/tests/test_protocol.py
- gufe/tests/test_transformation.py
Fixes #303 
@hannahbaumann has been benchmarking with 2.1.0, but 2.1.1 should be identical with just an additional set of parameters for Xe: https://github.com/openforcefield/openff-forcefields/releases/tag/2024.01.0
> Update default off version to 2.1.1

- gufe/components/proteincomponent.py
I found this missing Ion reccently . We should add it,, as it is frequently used.
> Adding CA ions to parsing list - proteincomponent.py

- gufe/components/explicitmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
This PR fixes #325 by ensuring user charges set at the molecule level are also set at the atom level which is how OpenFF detects them.
> Improve partial charge check

- gufe/tests/test_tokenization.py
- gufe/tokenization.py
This PR implements the `KeyedChain` representation for `GufeTokenizable`s originally implemented in 
[alchemiscale](https://github.com/openforcefield/alchemiscale). As it appears general and useful enough, an upstream implementation seems appropriate.
The `KeyedChain` representation encodes a `GufeTokenizable` as a list of Tuples with the `GufeKey` and keyed dicts of other required tokenizables as their first and second elements, respectively. These tokenizables are sorted such that, when decoded in order, all required dependencies have been satisfied while accounting for duplicated dependencies down the tree structure. This representation is particularly useful when encoding/decoding `GufeTokenizables` on systems without a populated `TOKENIZATION_REGISTRY`.
> Add KeyedChain GufeTokenizable representation

- gufe/protocols/protocoldag.py
- gufe/tests/test_protocol.py
Not sure how to add tests for this behavior. Please check if you can reproduce the original issue https://github.com/OpenFreeEnergy/gufe/issues/314
> Proposed fix to dag ordering

- docs/guide/serialization.rst
- gufe/tests/test_tokenization.py
- gufe/tokenization.py
Implements #359.
This adds convenience methods to the `GufeTokenizable` class to aid easy serialisation to and from JSON using the `keyed_chain` pattern which keeps the JSON objects small. 
@dotsdl I like the idea of having a serialisation module but noticed I would have to move the `JSON_HANDLER` which is a large API break so I went for the easier option for now. 
For the `from_json` method I wasn't quite sure how to handle filelike vs  JSON object input, Do you have any ideas? 
I noticed the [Transformation](https://docs.openfree.energy/en/stable/cookbook/dumping_transformation.html) object has saving and loading from JSON already with its `dump/load` methods do we want to keep these and route them through the new `to/from_json` methods and remove them later?
If we are happy with this …
> JSON serialization on `GufeTokenizable`

- gufe/tests/test_alchemicalnetwork.py
- gufe/tests/test_chemicalsystem.py
- gufe/tests/test_ligand_network.py
- gufe/tests/test_ligandatommapping.py
- gufe/tests/test_mapping.py
- gufe/tests/test_proteincomponent.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocolresult.py
- gufe/tests/test_serialization_migration.py
- gufe/tests/test_smallmoleculecomponent.py
- gufe/tests/test_solvents.py
- gufe/tests/test_tokenization.py
- gufe/tests/test_transformation.py
We do not consider `gufe` keys to be stable across versions, though they should be stable in-process and generally across machines running the same software versions. We only rely on them being stable in-process, however.
> Removed all hardcoded gufe keys from GufeTokenizable tests in test suite

- gufe/ligandnetwork.py
addresses https://github.com/OpenFreeEnergy/gufe/issues/360. 
hopefully this is more clear (and also correct).
> adding to LigandNetwork docstring

- .github/workflows/conda_cron.yaml
- environment.yml
This should fix any issues we've had lately.
> Fixing the conda cron

- gufe/network.py
- gufe/tests/conftest.py
- gufe/tests/test_alchemicalnetwork.py
> 383 get connected subgraphs in an alchemicalnetwork

- .github/workflows/ci.yaml
- .github/workflows/conda_cron.yaml
closes https://github.com/OpenFreeEnergy/gufe/issues/313
minimum supported macos should be 14.
> switch from macos-12 pin to macos-latest

- .github/workflows/conda_cron.yaml
I think we accidentally left the PR trigger from this action - it should only be run as a CRON job and never on PRs/merge.
> Remove PR trigger from conda_cron

- gufe/mapping/__init__.py
- gufe/mapping/errors.py
Fixes #419. This error should be raised by the derived atom mappers when there is an issue generating mappings.
Tips
Checklist
> Add `AtomMappingError`

- gufe/protocols/errors.py
- gufe/protocols/protocolunit.py
- gufe/tests/test_protocolunit.py
- news/add_execution_interrupt.rst
> add ExecutionInterrupt (special exception)

- gufe/components/explicitmoleculecomponent.py
- gufe/tests/test_explicitmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
Addresses #330 
We decided to use `logger.info`, since it is encouraged for users to pre-set partial charges, and we shouldn't be yelling at them for that.
Tips
Checklist
> switch user-set partial charges warning to log.info

- gufe/components/explicitmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
- gufe/tests/test_tokenization.py
- news/partial_charge_sum_fix.rst
Currently, if the net charge on a molecule is negative, the `Sum of partial charges differs` error does not get raised. I updated the check so that it's evaluating the absolute value of the difference between expected and calculated net charge.
Checklist
> partial charge checking - throw error for negative net charge diff

- gufe/protocols/protocol.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocoldag.py
- news/protocol_settings_class.rst
Require Protocol authors to define the _settings_cls attribute for their class. __init__ method checks that _settings_cls is define (if not raise NotImplementedError) and that the passed settings are an instance of the _settings_cls (if not raise ValueError).
Update existing Protocols in gufe to reflect this change. Closes #405.
Tips
Checklist
> Enforce protocol settings at instantiation

- gufe/components/explicitmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
- news/partial_charge_warning_to_logger.rst
Based off conversation with @dotsdl and @jthorton, we decided to update this logging message to include more molecular identifying information.
Tips
Checklist
- [ x] I certify that this contribution is covered by the MIT License [here](https://github.com/OpenFreeEnergy/openfe/blob/main/LICENSE) and the **Developer Certificate of Origin** at <https://developercertificate.org/>.
> Update partial charge check

- .github/workflows/ci.yaml
- .github/workflows/conda_cron.yaml
- .github/workflows/mypy.yaml
- news/partial_charge_warning_to_logger.rst
Tips
Checklist
This makes sure we use a default shell that will throw errors has they happen. This also drops the rdkit pin in the mypy tests since that has been fixed upstream.
> Use correct default shell

- gufe/components/explicitmoleculecomponent.py
- gufe/tests/test_tokenization.py
- gufe/tests/test_transformation.py
- gufe/tokenization.py
- gufe/transformations/transformation.py
- news/serialization-harmonization.rst
Closes #375, #458.
Also allows us to read `GufeTokenizable`s serialized previously in
`dict` representation via `.from_json`.
Tips
Checklist
> Added deprecation warning to Transformation.dump/load; removed ExplicitMoleculeComponent.to_json/from_json

- gufe/components/smallmoleculecomponent.py
- news/smallmoleculecomponent-openff-hydrogens.rst
Closes #297.
Adds `hydrogens_are_explicit=True` to `SmallMoleculeComponent.to_openff()`
Tips
Checklist
> Add explicit hydrogens kwarg to OpenFF export in SmallMoleculeComponent

- gufe/visualization/mapping_visualization.py
- news/issue-541.rst
Fixes #541 
Looking at the rdkit changelog, I suspect bond highlighting was actually not working properly before (and that rdkit just wasn't tripping on the attribute error because of some C++ / Python interface issue).
Checklist
> Fix typo in visualization

- environment.yml
- gufe/tests/conftest.py
- gufe/tests/test_proteincomponent.py
Host the data on zenodo as we get 403 errors from github sometimes.
Tips
Checklist
> Move data to zenodo

- .github/workflows/conda_cron.yaml
> Fix conda-cron: add pooch to test dependencies

- pyproject.toml
Eventually (2026-Feb-18) the license field needs to be a SPDX license expression. The table with a "file" or "text" key is deprecated. As of version 77.0.3, setuptools supports this new format.
See:
https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
Tips
Checklist
> Ensure PEP-639 Support
