- gufe/__init__.py
- gufe/component.py
- gufe/ligandcomponent.py
- gufe/proteincomponent.py
> Added Components parent class

- gufe/proteincomponent.py
- gufe/tests/test_chemicalsystem.py
- gufe/tests/test_protein_molecule.py
Optionally, makes `from_pdbfile` populate a secret `_openmm_rep` attribute, which holds a `PDBFile`.  Not a huge fan, but I think this is the best solution for now.
> WIP: nasty hack, optionally load a PDBFile in from_pdb for now

- gufe/tests/test_transformation.py
- gufe/tests/test_utils.py
- gufe/transformations/transformation.py
- gufe/utils.py
> Transformation dump

- gufe/components/proteincomponent.py
- gufe/custom_json.py
- gufe/network.py
- gufe/protocols/protocol.py
- gufe/protocols/protocoldag.py
fixes issue #93
we fortran now
> mypy: Fixing implicit None errors

- gufe/protocols/protocoldag.py
> change default of execute_DAG shared to cwd

- gufe/protocols/protocoldag.py
- gufe/protocols/protocolunit.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocol_unit.py
This PR will be a grab-bag of changes to ProtocolDAGResult and friends from results handling development in `fah-alchemy`.
Trying to keep number of changes to minimum necessary.
> [WIP] Various result handling improvements from working on `fah-alchemy`

- gufe/protocols/protocoldag.py
Sorry @richardjgowers, my trigger finger was too jumpy on #102 and I forgot to push these.
> Follows #102; meant to push doc fixes.

- gufe/protocols/protocol.py
> type annotations for ProtocolResult

- gufe/components/explicitmoleculecomponent.py
- gufe/components/smallmoleculecomponent.py
- gufe/tests/conftest.py
- gufe/tests/data/ethane.sdf
- gufe/tests/test_smallmoleculecomponent.py
> True flyweight 2

- gufe/components/smallmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
> Issue 154 smc roundtrip

- gufe/mapping/atom_mapping.py
- gufe/mapping/ligandatommapping.py
@ijpulidos: Does this clarify sufficiently?
If so, resolves #155.
> Clarify docstring for componentA_to_componentB

- gufe/components/solventcomponent.py
- gufe/tests/conftest.py
- gufe/tests/test_solvents.py
> Change ion default to something useful

- gufe/protocols/protocoldag.py
- gufe/tests/test_execute_dag.py
- gufe/tests/test_tokenization.py
- gufe/tokenization.py
@dotsdl I tried to write tests for your PR
> Alchemiscale compute 2

- gufe/settings/__init__.py
- gufe/settings/models.py
Last I heard it was  OpenFF not OpenF 🙃
> A hill I'm ready to die upon [nomenclature changes]

- .github/workflows/ci.yaml
- .github/workflows/conda_cron.yaml
- devtools/raise-or-close-issue.py
Included in this PR:
- package build & test on CI
- daily cron conda install & test
> Package test on CI

- gufe/chemicalsystem.py
- gufe/tests/test_chemicalsystem.py
- gufe/tests/test_network.py
- gufe/tests/test_transformation.py
was causing trouble in eq situations
> remove box_vector from ChemicalSystem

- gufe/settings/models.py
- gufe/tests/test_custom_json.py
- gufe/tests/test_protocol.py
- gufe/tests/test_transformation.py
Fixes #181 
This will change defaujlt settings in downstream protocols, so pinging @ijpulidos and @dotsdl too.
> Change default hydrogen mass to 3.0 amu

- environment.yml
- gufe/components/smallmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
related to openfreeenergy/openfe#278
> Openfe issue 278

- environment.yml
- gufe/tests/test_protocol.py
- gufe/tests/test_transformation.py
FloatQuantities in Settings are now cast to float even if integers were used as input
updated related hashes
> updated off models pin to 0.0.5

- gufe/custom_codecs.py
- gufe/protocols/protocolunit.py
- gufe/tests/test_protocol.py
- gufe/tests/test_tokenization.py
- gufe/tokenization.py
basic start/end times
probably not all we want to add, but definitely something we do want to add.
> Issue 168 basic telemetry

- gufe/protocols/protocol.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocoldag.py
> remove get_rate_of_convergence

- environment.yml
This is the current suggestion in https://github.com/openforcefield/openff-units/issues/69.
> Pin openff-units, pint to avoid typing issues

- gufe/protocols/protocolunit.py
Allows for compatibility with previously-stored ProtocolDAGResult.
> Makes start_time, end_time optional args for ProtocolUnitResult

- environment.yml
Just saw our cron CI jobs failed last night.
> Pin autodoc_pydantic

- gufe/protocols/protocol.py
- gufe/tests/test_protocol.py
- gufe/tests/test_protocolresult.py
> Fixes ProtocolResult.from_dict

- docs/guide/serialization.rst
- gufe/custom_codecs.py
- gufe/tests/test_custom_json.py
- gufe/tokenization.py
> Add NPY dtype codec

- gufe/components/smallmoleculecomponent.py
- gufe/tests/test_smallmoleculecomponent.py
> Support `name` in `SmallMoleculeComponent.copy_with_replacements`

- .github/workflows/ci.yaml
- .github/workflows/conda_cron.yaml
See: https://github.com/OpenFreeEnergy/openfe/issues/842
> Pin CI to macos-12

- README.md
> Mention 1.0 Release

- gufe/__init__.py
- gufe/mapping/__init__.py
- gufe/mapping/atom_mapping_scorer.py
- gufe/tests/test_setup_interfaces.py
update atom_mapping scorer definition
> Adding atom mapping scorer

- gufe/tests/test_tokenization.py
- gufe/tokenization.py
> Added some convenience methods to KeyedChain for symmetry; test simplifications

- environment.yml
resolves https://github.com/OpenFreeEnergy/gufe/issues/456
conda-forge feedstock PR: https://github.com/conda-forge/gufe-feedstock/pull/45
Tips
Checklist
> exclude rdkit 2024.03.06

- pyproject.toml
Tips
Checklist
The deps are nonfunctional since they don't give you everything you need, and including them pulls in networkx via pip instead of conda-forge (which can cause problems) if you forget a `--no-deps`
The optional testing deps are the same, they don't give you everything you need to test the package.
> remove deps in pyproject.toml

- docs/index.rst
resolves https://github.com/OpenFreeEnergy/gufe/issues/496
Tips
Checklist
> adding content to landing page

- .github/workflows/conda_cron.yaml
we shouldn't be testing the conda build on python 3.13 yet!
resolves https://github.com/OpenFreeEnergy/gufe/issues/591 and https://github.com/OpenFreeEnergy/gufe/issues/590
Tips
Checklist
> fix conda cron

- docs/environment.yaml
- gufe/protocols/protocoldag.py
> bump docs python version from 3.10 to 3.12

- docs/environment.yaml
In the interest of keeping our docs env build small, we should remove anything unnecessary. 
Tips
Checklist
> remove unneeded channel from env build
